version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  mock-bank:
    build: ./mock-bank
    ports: ["4000:4000"]

  api:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/reconcile_db
      - BANK_API_BASE=http://mock-bank:4000
      - RECONCILE_CRON=0 3 * * *
    depends_on: [ mongo, mock-bank ]
    ports: ["3000:3000"]

  web:
    build: ./frontend-dashboard
    environment:
      - API_BASE=http://api:3000/api
    depends_on: [ api ]
    ports: ["8080:80"]

volumes:
  mongo_data:
